/**
 * This code was generated by Builder.io.
 */
import React from "react";

type AddonCardProps = {
  title: string;
};

const AddonCard: React.FC<AddonCardProps> = ({ title }) => {
  return (
    <div className="flex flex-col px-8 py-11 bg-white rounded-3xl border border-solid border-black border-opacity-10 min-h-[210px] min-w-[240px] w-[550px] max-md:px-5 max-md:max-w-full">
      <h3 className="w-full text-2xl font-semibold leading-none text-zinc-800 max-md:max-w-full">
        {title}
      </h3>
      <button className="px-8 py-2.5 mt-12 max-w-full text-base font-bold text-white bg-blue-400 rounded-[100px] w-[482px] max-md:px-5 max-md:mt-10 hover:bg-blue-500 transition-colors">
        Book This Addon
      </button>
    </div>
  );
};

export default AddonCard;
