/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Footer: React.FC = () => {
  return (
    <footer className="flex flex-col px-20 py-14 w-full text-base text-white bg-blue-400 max-md:px-5 max-md:mr-2.5 max-md:max-w-full">
      <div className="flex flex-wrap gap-10 justify-between items-start w-full max-md:max-w-full">
        <p className="leading-6 w-[230px]">
          We make sure to give your car the pampering it deserves in BubBlast.
        </p>
        <nav className="flex flex-wrap gap-10 items-start min-w-[240px] max-md:max-w-full">
          <div className="flex flex-col">
            <h4 className="font-bold">Company</h4>
            <ul className="flex flex-col mt-6">
              <li className="mt-2 opacity-75">
                <a href="#" className="hover:text-blue-200">
                  About Us
                </a>
              </li>
              <li className="mt-2 opacity-75">
                <a href="#" className="hover:text-blue-200">
                  Our Services
                </a>
              </li>
              <li className="mt-2 opacity-75">
                <a href="#" className="hover:text-blue-200">
                  Pricing Plan
                </a>
              </li>
              <li className="mt-2 opacity-75">
                <a href="#" className="hover:text-blue-200">
                  Work with Us
                </a>
              </li>
              <li className="mt-2 opacity-75">
                <a href="#" className="hover:text-blue-200">
                  Automotive Blog
                </a>
              </li>
            </ul>
          </div>
          <div className="flex flex-col">
            <h4 className="font-bold">Support</h4>
            <ul className="flex flex-col mt-6">
              <li className="mt-2 opacity-75">
                <a href="#" className="hover:text-blue-200">
                  Service FAQ
                </a>
              </li>
              <li className="mt-2 opacity-75">
                <a href="#" className="hover:text-blue-200">
                  User Policy
                </a>
              </li>
              <li className="mt-2 opacity-75">
                <a href="#" className="hover:text-blue-200">
                  Privacy Policy
                </a>
              </li>
              <li className="mt-2 opacity-75">
                <a href="#" className="hover:text-blue-200">
                  Members Policy
                </a>
              </li>
              <li className="mt-2 opacity-75">
                <a href="#" className="hover:text-blue-200">
                  Customer Support
                </a>
              </li>
            </ul>
          </div>
          <div className="flex flex-col">
            <h4 className="font-bold">Contact</h4>
            <ul className="flex flex-col mt-6">
              <li className="mt-2 opacity-75">
                <a href="#" className="hover:text-blue-200">
                  Phone Number
                </a>
              </li>
              <li className="mt-2 opacity-75">
                <a href="#" className="hover:text-blue-200">
                  Email Address
                </a>
              </li>
              <li className="mt-2 opacity-75">
                <a href="#" className="hover:text-blue-200">
                  Our Locations
                </a>
              </li>
              <li className="mt-2 opacity-75">
                <a href="#" className="hover:text-blue-200">
                  Social Media
                </a>
              </li>
              <li className="mt-2 opacity-75">
                <a href="#" className="hover:text-blue-200">
                  Message Form
                </a>
              </li>
            </ul>
          </div>
        </nav>
        <div className="flex flex-col min-w-[240px]">
          <h4 className="font-bold">Newsletter</h4>
          <p className="mt-6 opacity-75">
            Subscribe to get monthly promo updates.
          </p>
          <form className="flex gap-10 items-start pb-4 mt-24 border-b border-solid border-b-white max-md:mt-10">
            <label htmlFor="emailInput" className="sr-only">
              Email Address
            </label>
            <input
              id="emailInput"
              type="email"
              placeholder="Email Address ..."
              className="bg-transparent border-none text-white placeholder-white placeholder-opacity-50 focus:outline-none"
            />
            <button type="submit" className="font-bold text-right">
              Subscribe
            </button>
          </form>
        </div>
      </div>
      <div className="flex flex-wrap gap-10 justify-between items-start mt-16 w-full max-md:mt-10 max-md:max-w-full">
        <p className="opacity-50">Copyright © 2023. All rights reserved.</p>
        <p className="text-right opacity-50">
          <a href="#" className="hover:text-blue-200">
            Privacy Policy
          </a>{" "}
          |{" "}
          <a href="#" className="hover:text-blue-200">
            Terms & Condition
          </a>
        </p>
      </div>
    </footer>
  );
};

export default Footer;
