/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface FooterProps {
  companyDescription: string;
  companyLinks: string[];
  supportLinks: string[];
  contactLinks: string[];
}

const Footer: React.FC<FooterProps> = ({
  companyDescription,
  companyLinks,
  supportLinks,
  contactLinks,
}) => {
  return (
    <footer className="flex flex-col px-20 py-14 w-full text-base text-white bg-blue-400 max-md:px-5 max-md:max-w-full">
      <div className="flex flex-wrap gap-10 justify-between items-start w-full max-md:max-w-full">
        <p className="leading-6 w-[230px]">{companyDescription}</p>
        <div className="flex flex-wrap gap-10 items-start min-w-[240px] max-md:max-w-full">
          <div className="flex flex-wrap gap-10 items-start min-w-[240px] max-md:max-w-full">
            <nav className="flex flex-col">
              <h3 className="font-bold">Company</h3>
              <ul className="flex flex-col mt-6 list-none pl-0">
                {companyLinks.map((link, index) => (
                  <li key={index} className="mt-2 opacity-75">
                    <a href="#" className="text-white hover:text-blue-100">
                      {link}
                    </a>
                  </li>
                ))}
              </ul>
            </nav>
            <nav className="flex flex-col">
              <h3 className="font-bold">Support</h3>
              <ul className="flex flex-col mt-6 list-none pl-0">
                {supportLinks.map((link, index) => (
                  <li key={index} className="mt-2 opacity-75">
                    <a href="#" className="text-white hover:text-blue-100">
                      {link}
                    </a>
                  </li>
                ))}
              </ul>
            </nav>
            <nav className="flex flex-col">
              <h3 className="font-bold">Contact</h3>
              <ul className="flex flex-col mt-6 list-none pl-0">
                {contactLinks.map((link, index) => (
                  <li key={index} className="mt-2 opacity-75">
                    <a href="#" className="text-white hover:text-blue-100">
                      {link}
                    </a>
                  </li>
                ))}
              </ul>
            </nav>
          </div>
          <div className="flex flex-col min-w-[240px]">
            <div className="flex flex-col self-start">
              <h3 className="font-bold">Newsletter</h3>
              <p className="mt-6 opacity-75">
                Subscribe to get monthly promo updates.
              </p>
            </div>
            <form className="flex gap-10 items-start pb-4 mt-24 border-b border-solid border-b-white max-md:mt-10">
              <label htmlFor="emailInput" className="sr-only">
                Email Address
              </label>
              <input
                type="email"
                id="emailInput"
                placeholder="Email Address ..."
                className="opacity-50 bg-transparent border-none outline-none"
                aria-label="Email Address"
              />
              <button type="submit" className="font-bold text-right">
                Subscribe
              </button>
            </form>
          </div>
        </div>
      </div>
      <div className="flex flex-wrap gap-10 justify-between items-start mt-16 w-full max-md:mt-10 max-md:max-w-full">
        <p className="opacity-50">Copyright © 2023. All rights reserved.</p>
        <p className="text-right opacity-50">
          <a href="#" className="text-white hover:text-blue-100">
            Privacy Policy
          </a>{" "}
          |{" "}
          <a href="#" className="text-white hover:text-blue-100">
            Terms & Condition
          </a>
        </p>
      </div>
    </footer>
  );
};

export default Footer;
