/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface HeaderProps {
  logo: string;
  menuItems: string[];
}

const Header: React.FC<HeaderProps> = ({ logo, menuItems }) => {
  return (
    <header className="flex relative z-10 flex-col justify-center items-center self-stretch px-16 py-3 w-full text-base bg-neutral-900 max-md:px-5 max-md:max-w-full">
      <div className="flex flex-wrap gap-10 w-full max-w-[1157px] max-md:max-w-full">
        <div className="flex flex-wrap flex-auto gap-7 text-white whitespace-nowrap max-md:max-w-full">
          <img
            loading="lazy"
            src={logo}
            alt="Company logo"
            className="object-contain shrink-0 aspect-square w-[71px]"
          />
          <nav className="flex flex-wrap flex-auto gap-10 items-start px-48 my-auto max-md:px-5 max-md:max-w-full">
            {menuItems.map((item, index) => (
              <a
                key={index}
                href="#"
                className="text-white hover:text-blue-400"
              >
                {item}
              </a>
            ))}
          </nav>
        </div>
        <button className="self-start px-8 py-2.5 mt-5 text-blue-400 border border-blue-400 border-solid rounded-[100px] max-md:px-5 hover:bg-blue-400 hover:text-white transition-colors">
          Contact Us
        </button>
      </div>
    </header>
  );
};

export default Header;
