/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ButtonProps {
  children: React.ReactNode;
  variant: "primary" | "secondary";
}

export const Button: React.FC<ButtonProps> = ({ children, variant }) => {
  const baseClasses = "self-stretch px-8 py-2.5 rounded-[100px] max-md:px-5";
  const variantClasses =
    variant === "primary"
      ? "bg-blue-400"
      : "border border-blue-400 border-solid";

  return (
    <button className={`${baseClasses} ${variantClasses}`}>{children}</button>
  );
};
