/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface FeatureListProps {
  features: string[];
}

export const FeatureList: React.FC<FeatureListProps> = ({ features }) => {
  return (
    <ul className="mt-10">
      {features.map((feature, index) => (
        <li key={index} className="mt-1.5 max-md:ml-2.5">
          {feature}
        </li>
      ))}
    </ul>
  );
};
