/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ServiceCardProps {
  title: string;
  description: string;
  iconColor?: string;
  textColor?: string;
  backgroundColor?: string;
}

const ServiceCard: React.FC<ServiceCardProps> = ({
  title,
  description,
  iconColor = "bg-zinc-400",
  textColor = "text-zinc-800",
  backgroundColor = "bg-white",
}) => {
  return (
    <section
      className={`flex flex-col items-start p-6 w-full ${backgroundColor} rounded-3xl shadow-lg max-w-[326px] min-h-[232px] ${textColor} max-md:px-5`}
    >
      <div
        className={`flex w-16 h-16 ${iconColor} min-h-[64px] rounded-[100px]`}
        aria-hidden="true"
      />
      <div className="flex flex-col mt-8 w-full">
        <h3 className="text-2xl font-semibold leading-none">{title}</h3>
        <p className="mt-2 text-base leading-6 opacity-50">{description}</p>
      </div>
    </section>
  );
};

export default ServiceCard;
