/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ServiceCard from "./ServiceCard";

const services = [
  {
    title: "Interior Detailing",
    description: "Lorem Ipsum is simply dummy text of the printing and",
  },
  {
    title: "Exterior Wash",
    description: "Lorem Ipsum is simply dummy text of the printing and",
  },
  {
    title: "Wheel & Tire Cleaning",
    description: "Lorem Ipsum is simply dummy text of the printing and",
  },
  {
    title: "Hand Waxing",
    description: "Lorem Ipsum is simply dummy text of the printing and",
    textColor: "text-white",
    backgroundColor: "bg-transparent",
  },
];

const ServicesSection: React.FC = () => {
  return (
    <section className="flex relative flex-col items-center px-20 mt-24 w-full min-h-[1204px] max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/7195b9e3973162441b20aaa6c793d87a55b1ed43e90bdf776abdfa5d3d92ab37?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11"
        className="object-cover absolute inset-0 size-full"
        alt=""
      />
      <header className="flex relative flex-col items-center text-center text-zinc-800 max-md:max-w-full">
        <h2 className="self-stretch px-10 py-2.5 text-base tracking-widest whitespace-nowrap bg-white rounded-[100px] max-md:px-5">
          SERVICES
        </h2>
        <h1 className="mt-8 text-6xl font-semibold tracking-tighter leading-none max-md:max-w-full max-md:text-4xl">
          What We Do for Your Car
        </h1>
      </header>
      <div className="flex relative flex-wrap gap-10 justify-between items-start self-stretch mt-20 min-h-[724px] max-md:mt-10 max-md:max-w-full">
        <div className="flex flex-col min-w-[240px] text-zinc-800 w-[326px]">
          <ServiceCard {...services[0]} />
          <div className="mt-48 max-md:mt-10">
            <ServiceCard {...services[2]} />
          </div>
        </div>
        <div className="flex flex-col pt-20 min-w-[240px] w-[326px]">
          <ServiceCard {...services[1]} />
          <div className="mt-48 max-md:mt-10">
            <ServiceCard {...services[3]} />
          </div>
        </div>
      </div>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/5086ffe3f704400b84d9d7c8359de116af1b963d9316a16295eef23b10841324?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11"
        className="object-contain z-10 mt-0 max-w-full aspect-[0.55] w-[558px] max-md:mt-0"
        alt="Car detailing service illustration"
      />
    </section>
  );
};

export default ServicesSection;
