/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Hero from "./Hero";
import About from "./About";
import Services from "./Services";
import Testimonial from "./Testimonial";
import Partners from "./Partners";
import Pricing from "./Pricing";
import CallToAction from "./CallToAction";
import Footer from "./Footer";

const MainLayout: React.FC = () => {
  return (
    <div className="flex flex-col bg-white">
      <Header />
      <main>
        <Hero />
        <About />
        <Services />
        <Testimonial />
        <Partners />
        <Pricing />
        <CallToAction />
      </main>
      <Footer />
    </div>
  );
};

export default MainLayout;
