/**
 * This code was generated by Builder.io.
 */
import React from "react";

const partnerLogos = [
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/4aea4c71417580ee355df56f5b6f585d9083e48d6d8ea2992ed44ddb1e11d038?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11",
    alt: "Partner 1 logo",
    className:
      "object-contain shrink-0 self-stretch my-auto aspect-[4.26] w-[136px]",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/1cb62e3594b96e72862b628d4352ee768e025591efae6ceb19b5813f8d2efaef?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11",
    alt: "Partner 2 logo",
    className:
      "object-contain shrink-0 self-stretch my-auto aspect-[3.28] w-[105px]",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/cbf115cabe71ed5d86524f556c4d0810909b10740cd4661d273a6d408c6644d2?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11",
    alt: "Partner 3 logo",
    className:
      "object-contain shrink-0 self-stretch my-auto aspect-[4.07] w-[130px]",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/9dd0f633c98204a6898a97c2b15f3a6c198abb87f030e467d3bce948ffa7f3f5?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11",
    alt: "Partner 4 logo",
    className:
      "object-contain shrink-0 self-stretch my-auto aspect-[3.79] w-[121px]",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/74410fc78f131dfb7117bd687592e8976669baf13b217c2fe1d99f75da0369fb?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11",
    alt: "Partner 5 logo",
    className:
      "object-contain shrink-0 self-stretch my-auto aspect-[3.47] w-[111px]",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/eff9f4b95309e49a07b5c5d727d73414c7917fbe4fd7baafaa98ca13b8889714?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11",
    alt: "Partner 6 logo",
    className:
      "object-contain shrink-0 self-stretch my-auto aspect-[5.78] w-[162px]",
  },
];

const Partners: React.FC = () => {
  return (
    <section className="flex flex-wrap gap-10 justify-between items-center px-20 mt-48 w-full min-h-[32px] max-md:px-5 max-md:mt-10 max-md:max-w-full">
      {partnerLogos.map((logo, index) => (
        <img
          key={index}
          loading="lazy"
          src={logo.src}
          alt={logo.alt}
          className={logo.className}
        />
      ))}
    </section>
  );
};

export default Partners;
