/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ServiceCardProps {
  title: string;
  description: string;
  iconSrc: string;
  isHighlighted?: boolean;
}

const ServiceCard: React.FC<ServiceCardProps> = ({
  title,
  description,
  iconSrc,
  isHighlighted = false,
}) => {
  const baseClasses =
    "flex flex-col p-10 rounded-3xl min-h-[240px] min-w-[240px] w-[400px] max-md:px-5";
  const highlightedClasses = isHighlighted
    ? "text-white bg-blue-400"
    : "bg-white text-zinc-800";

  return (
    <div className={`${baseClasses} ${highlightedClasses}`}>
      <img
        loading="lazy"
        src={iconSrc}
        alt=""
        className="object-contain w-10 aspect-square min-h-[40px]"
      />
      <div className="flex flex-col mt-8 w-full">
        <div className="flex flex-col w-full">
          <h3 className="text-2xl font-semibold leading-none">{title}</h3>
          <p
            className={`mt-2 text-base leading-6 ${
              isHighlighted ? "opacity-75" : "opacity-50"
            }`}
          >
            {description}
          </p>
        </div>
      </div>
    </div>
  );
};

export default ServiceCard;
