/**
 * This code was generated by Builder.io.
 */
import React from "react";

const HeroSection: React.FC = () => {
  return (
    <section className="flex flex-col items-center mt-28 max-md:mt-10">
      <h1 className="relative ml-3.5 text-7xl font-semibold tracking-tighter leading-none text-white max-md:text-4xl">
        About Us
      </h1>
      <p className="relative mt-10 mb-0 text-xl leading-8 text-center text-white w-[527px] max-md:mb-2.5 max-md:max-w-full">
        Lorem Ipsum is simply dummy text of the printing and typesetting
        industry. Lorem Ipsum has
      </p>
    </section>
  );
};

export default HeroSection;
