/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ButtonProps {
  children: React.ReactNode;
  variant?: "solid" | "outline";
  className?: string;
}

const Button: React.FC<ButtonProps> = ({
  children,
  variant = "solid",
  className = "",
}) => {
  const baseClasses =
    "px-8 py-2.5 rounded-[100px] font-bold transition-colors max-md:px-5";
  const variantClasses =
    variant === "outline"
      ? "text-blue-400 border border-blue-400 hover:bg-blue-400 hover:text-white"
      : "text-white bg-neutral-950 hover:bg-blue-500";

  return (
    <button className={`${baseClasses} ${variantClasses} ${className}`}>
      {children}
    </button>
  );
};

export default Button;
