/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ServicesSection from "./ServicesSection";

const CarServices: React.FC = () => {
  return (
    <main>
      <ServicesSection />
    </main>
  );
};

export default CarServices;
