/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import Header from '../Header';
import Hero from './Hero';
import Stats from './Stats';
import Services from './Services';
import Partners from './Partners';
import Footer from './Footer';

const CarWashService: React.FC = () => {
  const navItems = ['About', 'Services', 'Pricing', 'Blog'];
  const stats = [
    { value: '8,000+', label: 'Satisfied Clients' },
    { value: '150+', label: 'Car Models' },
    { value: '98%', label: 'Succession Rate' },
  ];
  const services = [
    {
      title: 'Interior Detailing',
      description: 'a cleaning of the inner parts of a vehicle including leather, ....',
      iconSrc: 'https://cdn.builder.io/api/v1/image/assets/TEMP/0c4bc369c732b4bf6c2901ab1bca691d6d2e06d1de98a4dfca45c66314e542b8?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11',
    },
    {
      title: 'Exterior Wash',
      description: 'Exterior detailing involves cleaning, and either restoring ...',
      iconSrc: 'https://cdn.builder.io/api/v1/image/assets/TEMP/0c4bc369c732b4bf6c2901ab1bca691d6d2e06d1de98a4dfca45c66314e542b8?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11',
    },
    {
      title: 'Wheel & Tire Cleaning',
      description: 'breaking down stubborn brake dust, industrial fallout, and....',
      iconSrc: 'https://cdn.builder.io/api/v1/image/assets/TEMP/0c4bc369c732b4bf6c2901ab1bca691d6d2e06d1de98a4dfca45c66314e542b8?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11',
      isHighlighted: true,
    },
    {
      title: 'Hand Waxing',
      description: 'Hand wax is better than spray wax as wax applied by hand ...',
      iconSrc: 'https://cdn.builder.io/api/v1/image/assets/TEMP/0c4bc369c732b4bf6c2901ab1bca691d6d2e06d1de98a4dfca45c66314e542b8?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11',
    },
  ];
  const partnerLogos = [
    'https://cdn.builder.io/api/v1/image/assets/TEMP/903e8052b5a673bbb033ae023dcfe207540eb59021efa006d9fe3bb97204aeb9?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11',
    'https://cdn.builder.io/api/v1/image/assets/TEMP/1cb62e3594b96e72862b628d4352ee768e025591efae6ceb19b5813f8d2efaef?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11',
    'https://cdn.builder.io/api/v1/image/assets/TEMP/965b125e4eda30d359030819404d264ca876115cba52c3a3e3472c34d850d975?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11',
    'https://cdn.builder.io/api/v1/image/assets/TEMP/29299195c0ec496819dda26ce7d19a4cb2df35dc3acab34f02e03a5f96029fa1?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11',
    'https://cdn.builder.io/api/v1/image/assets/TEMP/da581b665dacc30b936d27da591f95b9edafc4390ed698ae208155164194419a?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11',
    'https://cdn.builder.io/api/v1/image/assets/TEMP/bb48de0754655eadca732aac3f0ae7337f2eaeae2a2e0abf3fce9d1b52ff6ce1?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11',
  ];
  const footerSections = [
    {
      title: 'Company',
      links: [
        { label: 'About Us', href: '#' },
        { label: 'Our Services', href: '#' },
        { label: 'Pricing Plan', href: '#' },
        { label: 'Work with Us', href: '#' },
        { label: 'Automotive Blog', href: '#' },
      ],
    },
    {
      title: 'Support',
      links: [
        { label: 'Service FAQ', href: '#' },
        { label: 'User Policy', href: '#' },
        { label: 'Privacy Policy', href: '#' },
        { label: 'Members Policy', href: '#' },
        { label: 'Customer Support', href: '#' },
      ],
    },
    {
      title: 'Contact',
      links: [
        { label: 'Phone Number', href: '#' },
        { label: 'Email Address', href: '#' },
        { label: 'Our Locations', href: '#' },
        { label: 'Social Media', href: '#' },
        { label: 'Message Form', href: '#' },
      ],
    },
  ];

  return (
    <div className="flex flex-col bg-white">
      <Header logoSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/0c4bc369c732b4bf6c2901ab1bca691d6d2e06d1de98a4dfca45c66314e542b8?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11" navItems={navItems} />
      <main>
        <Hero
          backgroundSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/2666b63e56047f781d7ce3108dfd3695df328b40fe68b68630ace732ee6dfd60?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11"
          title="Service"
          description="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has"
        />
        <section className="self-center mt-20 text-2xl font-semibold leading-7 text-center text-black max-md:mt-10 max-md:max-w-full">
          Our sole objective is to collaborate with our clients to deliver the best solutions for their goals.
          Our leadership, staff, and experience are what set us apart—you'll always be a priority working with us.
        </section>
        <Stats stats={stats} />
        <Services services={services} />
        <Partners logos={partnerLogos} />
        <Footer
          description="We make sure to give your car the pempering it deserves in BubBlast."
          sections={footerSections}
        />
      </main>
    </div>
  );
};

export default CarWashService;