/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface FooterLink {
  label: string;
  href: string;
}

interface FooterSection {
  title: string;
  links: FooterLink[];
}

interface FooterProps {
  description: string;
  sections: FooterSection[];
}

const Footer: React.FC<FooterProps> = ({ description, sections }) => {
  return (
    <footer className="flex flex-col px-20 py-14 mt-24 w-full text-base text-white bg-blue-400 max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <div className="flex flex-wrap gap-10 justify-between items-start w-full max-md:max-w-full">
        <div className="leading-6 w-[230px]">{description}</div>
        <div className="flex flex-wrap gap-10 items-start min-w-[240px] max-md:max-w-full">
          {sections.map((section, index) => (
            <div key={index} className="flex flex-col">
              <h3 className="font-bold">{section.title}</h3>
              <nav className="flex flex-col mt-6">
                {section.links.map((link, linkIndex) => (
                  <a
                    key={linkIndex}
                    href={link.href}
                    className="mt-2 opacity-75 hover:opacity-100 transition-opacity"
                  >
                    {link.label}
                  </a>
                ))}
              </nav>
            </div>
          ))}
          <div className="flex flex-col min-w-[240px]">
            <div className="flex flex-col self-start">
              <h3 className="font-bold">Newsletter</h3>
              <p className="mt-6 opacity-75">
                Subscribe to get monthly promo updates.
              </p>
            </div>
            <form className="flex gap-10 items-start pb-4 mt-24 border-b border-solid border-b-white max-md:mt-10">
              <label htmlFor="email" className="sr-only">
                Email Address
              </label>
              <input
                type="email"
                id="email"
                placeholder="Email Address ..."
                className="bg-transparent border-none outline-none text-white placeholder-white placeholder-opacity-50 flex-grow"
                required
              />
              <button type="submit" className="font-bold text-right">
                Subscribe
              </button>
            </form>
          </div>
        </div>
      </div>
      <div className="flex flex-wrap gap-10 justify-between items-start mt-16 w-full max-md:mt-10 max-md:max-w-full">
        <div className="opacity-50">Copyright © 2023. All rights reserved.</div>
        <div className="text-right opacity-50">
          <a href="/privacy" className="hover:underline">
            Privacy Policy
          </a>{" "}
          |{" "}
          <a href="/terms" className="hover:underline">
            Terms & Condition
          </a>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
