/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Button from "./Button";

interface HeaderProps {
  logoSrc: string;
  navItems: string[];
}

const Header: React.FC<HeaderProps> = ({ logoSrc, navItems }) => {
  return (
    <header className="flex relative flex-col justify-center items-center self-stretch px-16 py-3 w-full bg-neutral-900 max-md:px-5 max-md:max-w-full">
      <nav className="flex flex-wrap gap-10 w-full max-w-[1157px] max-md:max-w-full">
        <div className="flex flex-wrap flex-auto gap-7 text-white whitespace-nowrap max-md:max-w-full">
          <img
            loading="lazy"
            src={logoSrc}
            alt="Company logo"
            className="object-contain shrink-0 aspect-square w-[71px]"
          />
          <div className="flex flex-wrap flex-auto gap-10 items-start px-48 my-auto max-md:px-5 max-md:max-w-full">
            {navItems.map((item, index) => (
              <a
                key={index}
                href={`#${item.toLowerCase()}`}
                className="text-white hover:text-blue-400 transition-colors"
              >
                {item}
              </a>
            ))}
          </div>
        </div>
        <Button variant="outline">Contact Us</Button>
      </nav>
    </header>
  );
};

export default Header;
