/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Button from "./Button";

interface HeroProps {
  backgroundSrc: string;
  title: string;
  description: string;
}

const Hero: React.FC<HeroProps> = ({ title, description }) => {
  return (
    <section className="flex relative flex-col items-center pb-20 w-full min-h-[542px] max-md:max-w-full">
      <img
        loading="lazy"
        src= "https://cdn.builder.io/api/v1/image/assets/TEMP/2666b63e56047f781d7ce3108dfd3695df328b40fe68b68630ace732ee6dfd60?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11"
        alt="Hero background"
        className="object-cover absolute inset-0 w-full h-full max-h-[600px]"
      />
      <div className="relative mt-28 text-7xl font-semibold tracking-tighter leading-none text-white max-md:mt-10 max-md:text-4xl">
        {title}
      </div>
      <p className="relative mt-10 ml-4 text-xl leading-8 text-center text-white w-[527px] max-md:max-w-full">
        {description}
      </p>
      <Button className="relative mt-10">Get in touch</Button>
    </section>
  );
};

export default Hero;
