/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ReactDOM from "react-dom";
import CarWashService from "./components/CarWashService";
import "./index.css";

ReactDOM.render(
  <React.StrictMode>
    <CarWashService />
  </React.StrictMode>,
  document.getElementById("root")
);
