/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ReactDOM from "react-dom";
import "./index.css";
import ServicesSection from "./ServicesSection";

ReactDOM.render(
  <React.StrictMode>
    <ServicesSection />
  </React.StrictMode>,
  document.getElementById("root")
);
