/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface PartnersProps {
  logos: string[];
}

const Partners: React.FC<PartnersProps> = ({ logos }) => {
  return (
    <div className="flex flex-wrap gap-10 justify-between items-center px-20 w-full min-h-[32px] mt-[659px] max-md:px-5 max-md:mt-10 max-md:max-w-full">
      {logos.map((logo, index) => (
        <img
          key={index}
          loading="lazy"
          src={logo}
          alt={`Partner logo ${index + 1}`}
          className="object-contain shrink-0 self-stretch my-auto"
        />
      ))}
    </div>
  );
};

export default Partners;
