/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ServiceCardProps {
  title: string;
  description: string;
  iconSrc: string;
  isHighlighted?: boolean;
}

const ServiceCard: React.FC<ServiceCardProps> = ({
  title,
  description,
  iconSrc,
  isHighlighted = false,
}) => {
  const baseClasses =
    "flex flex-col items-start px-9 py-10 w-full rounded-3xl shadow-lg min-h-[334px] max-md:px-5 max-md:mt-10 max-md:max-w-full";
  const colorClasses = isHighlighted
    ? "text-white bg-blue-400"
    : "bg-white text-zinc-800";

  return (
    <div className={`${baseClasses} ${colorClasses}`}>
      <img
        src={iconSrc}
        alt=""
        className="flex bg-zinc-400 h-[89px] min-h-[90px] rounded-[140px] w-[89px]"
      />
      <div className="flex flex-col mt-11 max-w-full w-[366px] max-md:mt-10">
        <h3 className="text-2xl font-semibold leading-8">{title}</h3>
        <p className="mt-3 text-base leading-6 opacity-50">{description}</p>
      </div>
    </div>
  );
};

export default ServiceCard;
