/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface Stat {
  value: string;
  label: string;
}

interface StatsProps {
  stats: Stat[];
}

const Stats: React.FC<StatsProps> = ({ stats }) => {
  return (
    <div className="flex flex-wrap gap-10 items-center self-center mt-24 max-md:mt-10 max-md:max-w-full">
      {stats.map((stat, index) => (
        <React.Fragment key={index}>
          {index > 0 && (
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/321c9c3857de93b4756f0d2c03db9a81b3567733dce420a078bf7f2ae429f28a?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto aspect-square fill-blue-400 w-[23px]"
            />
          )}
          <div className="flex flex-col self-stretch my-auto">
            <div className="text-5xl font-semibold tracking-tighter leading-none text-blue-400 max-md:text-4xl">
              {stat.value}
            </div>
            <div className="mt-1.5 text-2xl text-zinc-800">{stat.label}</div>
          </div>
        </React.Fragment>
      ))}
    </div>
  );
};

export default Stats;
