/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Layout from "./Layout";
import Hero from "./Heroabout";
import AboutSection from "./AboutSection";
import TeamSection from "./TeamSection";
import BlogPosts from "./BlogPosts";
import ServicesSection from "./ServicesSection";

const AboutPage: React.FC = () => {
  return (
    <Layout>
      <Hero />
      <AboutSection />
      <TeamSection />
      <BlogPosts />
      <ServicesSection />
    </Layout>
  );
};

export default AboutPage;
