/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Layout from "./Layout";
import Hero from "./Heroabout";
import TeamSection from "./TeamSection";
import BlogPosts from "./BlogPosts";
import ServicesSection from "./ServicesSection";
import AboutUs from "./AboutUs/AboutUs";
import WhoWeAre from "./whoweare/WhoWeAre";

const AboutPage: React.FC = () => {
  return (
    <Layout>
      <AboutUs />
      <WhoWeAre/>
      <BlogPosts />
      <ServicesSection />
    </Layout>
  );
};

export default AboutPage;
