/**
 * This code was generated by Builder.io.
 */
import React from "react";

const AboutSection: React.FC = () => {
  return (
    <section className="self-center mt-28 max-w-full w-[898px] max-md:mt-10">
      <div className="flex gap-5 max-md:flex-col">
        <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
          <div className="flex relative flex-col grow aspect-[0.823] max-md:mt-10">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/0804cf27599c0f1011f65471fe0d2fa338abe434b88e55a2eeebae2d5cc2b890?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11"
              alt="About us background"
              className="object-cover absolute inset-0 size-full"
            />
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/63f1d9eda55fb9e2cd5c6df3e0bc3b5773241be22daded90fc685cc361f0f568?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11"
              alt="About us foreground"
              className="object-contain w-full aspect-[0.82]"
            />
          </div>
        </div>
        <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
          <div className="flex flex-col items-start self-stretch my-auto w-full font-bold max-md:mt-10">
            <span className="text-xs tracking-widest leading-none uppercase text-zinc-400">
              about us
            </span>
            <h2 className="mt-6 text-5xl leading-none text-gray-900">
              Who We Are 
            </h2>
            <div className="shrink-0 mt-9 border-blue-400 border-solid border-[3px] h-[3px] w-[132px]" />
            <p className="mt-8 text-sm leading-loose text-zinc-500">
              Lorem ipsum dolor sit amet consectetur
            </p>
            <p className="self-stretch mt-9 text-sm leading-6 text-zinc-500">
              Lorem ipsum dolor sit amet consectetur. Tellus sit volutpat
              maecenas ut Vestibulum egestas in donec cras Sit id ultrices in
              duis imperdiet scelerisque molestie senectus elementum. Augue ac
              viverra ultrices veli
            </p>
            <button className="self-stretch px-8 py-2.5 mt-16 text-base text-white bg-blue-400 rounded-[100px] max-md:px-5 max-md:mt-10">
              Book Appointment
            </button>
          </div>
        </div>
      </div>
    </section>
  );
};

export default AboutSection;
