/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface BlogPost {
  image: string;
  title: string;
  date: string;
}

const blogPosts: BlogPost[] = [
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/e8110480a0ff23c565c9c8bff78a8672be2cfc481961eb1e68f9754535f97883?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11",
    title: "Lorem ipsum dolor sit amet consectetur. Sit lacinia est.",
    date: "December 12, 2022",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/d5e8b9403a865dc97e7a754552aab0eab443879693e55ddcbeaa6f1b7504e27e?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11",
    title: "Lorem ipsum dolor sit amet consectetur. Sed ornare massa.",
    date: "December 12, 2022",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/6925845d289edb95c6558475c94a7f4f504dcd85a3a9945af5480213e14a6ef2?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11",
    title: "Lorem ipsum dolor sit amet consectetur. Pulvinar.",
    date: "December 12, 2022",
  },
];

const BlogPostCard: React.FC<BlogPost> = ({ image, title, date }) => {
  return (
    <article className="flex overflow-hidden flex-col grow shrink bg-white rounded-md shadow-lg min-w-[240px] w-[222px]">
      <img
        loading="lazy"
        src={image}
        alt={title}
        className="object-contain max-w-full rounded-md aspect-[1.48] w-[278px]"
      />
      <div className="flex flex-col px-6 py-5 max-w-full bg-white rounded-md w-[278px] max-md:px-5">
        <h3 className="text-lg font-medium leading-5 text-slate-900">
          {title}
        </h3>
        <p className="mt-3 text-sm leading-relaxed text-white">
          {date} No comments
        </p>
      </div>
    </article>
  );
};

const BlogPosts: React.FC = () => {
  return (
    <section className="flex z-10 flex-wrap gap-6 items-start self-center mt-0 max-w-full h-[293px] w-[880px]">
      {blogPosts.map((post, index) => (
        <BlogPostCard key={index} {...post} />
      ))}
    </section>
  );
};

export default BlogPosts;
