/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Heroabout: React.FC = () => {
  return (
    <section className="flex relative flex-col items-center pb-28 w-full min-h-[491px] max-md:pb-24 max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/51f3959d6ec6eb25a028945413ac8aff50d901f9b1b584d34080538bf6fe4f55?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11"
        alt="Background image"
        className="object-cover absolute inset-0 size-full"
      />
      <h1 className="relative mt-28 ml-3.5 text-7xl font-semibold tracking-tighter leading-none text-white max-md:mt-10 max-md:text-4xl">
        About Us
      </h1>
      <p className="relative mt-10 mb-0 text-xl leading-8 text-center text-white w-[527px] max-md:mb-2.5 max-md:max-w-full">
        Lorem Ipsum is simply dummy text of the printing and typesetting
        industry. Lorem Ipsum has
      </p>
    </section>
  );
};

export default Heroabout;
