/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "../Header";
import Footer from "../Footer";

interface LayoutProps {
  children: React.ReactNode;
}

const Layout: React.FC<LayoutProps> = ({ children }) => {
  // Define the navItems array
  const navItems = ['Home', 'About Us', 'Services', 'Products']; // Example nav items

  return (
    <div className="flex flex-col bg-white">
      {/* Pass navItems to the Header component */}
      <Header navItems={navItems} />
      <main>{children}</main>
      <Footer />
    </div>
  );
};

export default Layout;
