/**
 * This code was generated by Builder.io.
 */
import React from "react";

const TeamSection: React.FC = () => {
  return (
    <section className="px-16 pt-12 pb-40 mt-28 text-5xl font-bold leading-10 text-center text-gray-900 bg-zinc-100 max-md:px-5 max-md:pb-28 max-md:mt-10 max-md:mr-2.5 max-md:max-w-full">
      <h2>We are a team of expert technicians</h2>
    </section>
  );
};

export default TeamSection;
