/**
 * This code was generated by Builder.io.
 */
import React from "react";
import PricingPage from "../PricingPage";

const Home: React.FC = () => {
  return <PricingPage />;
};

export default Home;
